name: Build Executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: dyno.exe
          - os: macos-latest
            output_name: dyno

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install matplotlib
      run: pip install matplotlib>=3.9.0

    - name: Install pyserial
      run: pip install pyserial>=3.5

    - name: Install pyinstaller
      run: pip install "pyinstaller>=6.11.0,<6.12.0"

    - name: Build executable
      run: |
        pyinstaller --name dyno \
                    --onedir \
                    --distpath dyno \
                    dyno/dyno.py

    - name: Handle executable
      shell: bash
      run: |
        mkdir -p dyno
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp dyno/dyno/dyno.exe dyno/dyno.exe
        else
          cp dyno/dyno/dyno dyno/dyno
          chmod +x dyno/dyno
        fi

    - name: Clean up build artifacts
      run: |
        rm -rf dyno/dyno
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dyno-${{ matrix.os }}
        path: dyno/${{ matrix.output_name }}
