name: Build and Release Dyno Executables
on:
  push:
    branches: [ master ]
    paths:
      - 'dyno/dyno.py'
      - '.github/workflows/build_dyno.yml'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      timeout-minutes: 5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      timeout-minutes: 5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      timeout-minutes: 10
      run: |
        pip install --timeout 600 -v --no-cache-dir pyoxidizer
        pip install --timeout 600 -v --no-cache-dir pyserial~=3.5
        pip install --timeout 600 -v --no-cache-dir matplotlib~=3.9.3

    - name: Create PyOxidizer config
      shell: pwsh
      run: |
        @"
        def make_exe():
            dist = default_python_distribution()
            policy = dist.make_python_packaging_policy()
            policy.resources_location = "filesystem-relative:lib"
            policy.resources_location_fallback = "filesystem-relative:lib"
            policy.allow_files = True
            policy.file_scanner_emit_files = True
            policy.include_distribution_resources = True
            policy.include_non_distribution_sources = True
            policy.include_test = False
            
            python_config = dist.make_python_interpreter_config()
            python_config.run_module = "dyno.dyno"
            python_config.module_search_paths = ["$ORIGIN", "$ORIGIN/lib"]
            
            exe = dist.to_python_executable(
                name = "dyno",
                packaging_policy = policy,
                config = python_config,
            )
            
            exe.add_python_resources(exe.pip_install(["pyserial==3.5", "matplotlib==3.9.3"]))
            exe.add_python_resources(exe.read_package_root(".", ["dyno"]))
            
            # Tell PyOxidizer about module files that should be copied into the bundle
            exe.add_in_memory_python_resources(dist.pip_install(["numpy"]))
            
            return exe

        # Tell PyOxidizer we want to build a single-file binary.
        def make_embedded():
            return VARS.get("PYOXIDIZER_EXE")

        register_target("exe", make_exe)
        resolve_targets()
        "@ | Out-File -FilePath pyoxidizer.bzl -Encoding UTF8
    
    - name: Build executable
      timeout-minutes: 10
      shell: pwsh
      run: |
        pyoxidizer build --release
        New-Item -Path dist -ItemType Directory -Force
        Move-Item build/x86_64-pc-windows-msvc/release/exe/dyno.exe dist/dyno-windows.exe
    
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: dist/dyno-windows.exe
        retention-days: 1

  build-macos:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      timeout-minutes: 5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      timeout-minutes: 5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      timeout-minutes: 10
      run: |
        pip install --timeout 600 -v --no-cache-dir pyoxidizer
        pip install --timeout 600 -v --no-cache-dir pyserial~=3.5
        pip install --timeout 600 -v --no-cache-dir matplotlib~=3.9.3
    
    - name: Create PyOxidizer config
      run: |
        cat > pyoxidizer.bzl << 'EOL'
        def make_exe():
            dist = default_python_distribution()
            policy = dist.make_python_packaging_policy()
            policy.resources_location = "filesystem-relative:lib"
            policy.resources_location_fallback = "filesystem-relative:lib"
            policy.allow_files = True
            policy.file_scanner_emit_files = True
            policy.include_distribution_resources = True
            policy.include_non_distribution_sources = True
            policy.include_test = False
            
            python_config = dist.make_python_interpreter_config()
            python_config.run_module = "dyno.dyno"
            python_config.module_search_paths = ["$ORIGIN", "$ORIGIN/lib"]
            
            exe = dist.to_python_executable(
                name = "dyno",
                packaging_policy = policy,
                config = python_config,
            )
            
            exe.add_python_resources(exe.pip_install(["pyserial==3.5", "matplotlib==3.9.3"]))
            exe.add_python_resources(exe.read_package_root(".", ["dyno"]))
            
            # Tell PyOxidizer about module files that should be copied into the bundle
            exe.add_in_memory_python_resources(dist.pip_install(["numpy"]))
            
            return exe

        # Tell PyOxidizer we want to build a single-file binary.
        def make_embedded():
            return VARS.get("PYOXIDIZER_EXE")

        register_target("exe", make_exe)
        resolve_targets()
        EOL
    
    - name: Build executable
      timeout-minutes: 10
      shell: bash
      run: |
        pyoxidizer build --release
        mkdir -p dist
        # Copy the entire build directory to preserve dependencies
        mv ./build/aarch64-apple-darwin/release/exe/* dist/
        cd dist
        # Create archive with all files
        tar czf dyno-mac.tgz *
    
    - name: Upload macOS build
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: dist/dyno-mac.tgz
        retention-days: 1

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the date and short SHA
          DATE=$(date +'%Y-%m-%d')
          SHA=$(git rev-parse --short HEAD)
          RELEASE_TAG="build-${DATE}-${SHA}"
          
          # Create release notes with Mac instructions
          cat > release_notes.md << 'EOL'
          Automated build from commit: $(git log -1 --pretty=%B)

          ## Mac Installation Instructions
          1. Download dyno-mac.tgz
          2. Open Terminal
          3. Navigate to Downloads: cd ~/Downloads
          4. Extract the archive: tar xzf dyno-mac.tgz
          5. Run the program: ./dyno

          Note: If you get a security warning, go to System Preferences > Security & Privacy and click "Open Anyway"
          EOL
          
          # Create release
          gh release create "$RELEASE_TAG" \
            --title "Dyno Build ${DATE} (${SHA})" \
            --notes-file release_notes.md \
            dist/windows-build/dyno-windows.exe \
            dist/macos-build/dyno-mac.tgz
