name: Build Dyno Executables
on:
  push:
    branches: [ master ]
    paths:
      - 'dyno/dyno.py'
      - '.github/workflows/build_dyno.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'dyno/dyno.py'
      - '.github/workflows/build_dyno.yml'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      timeout-minutes: 5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      timeout-minutes: 5
      with:
        python-version: '3.10'
    
    - name: Install cx_Freeze
      timeout-minutes: 10
      run: |
        pip install --timeout 600 -v --no-cache-dir cx_Freeze~=6.15.9

    - name: Install pyserial
      timeout-minutes: 10
      run: |
        pip install --timeout 600 -v --no-cache-dir pyserial~=3.5

    - name: Install matplotlib
      timeout-minutes: 10
      run: |
        pip install --timeout 600 -v --no-cache-dir matplotlib~=3.9.3
    
    - name: Create setup.py
      shell: pwsh
      run: |
        @"
        from cx_Freeze import setup, Executable
        
        setup(
            name="dyno",
            version="1.0",
            executables=[
                Executable(
                    "dyno/dyno.py",
                    target_name="dyno.exe",
                    base="console"
                )
            ]
        )
        "@ | Out-File -FilePath setup.py -Encoding UTF8

    - name: Build executable
      timeout-minutes: 10
      shell: pwsh
      run: |
        python setup.py build
        New-Item -Path dyno/bin -ItemType Directory -Force
        Move-Item build/exe.win*/dyno.exe dyno/bin/dyno-windows.exe
    
    - name: Configure Git and Push
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git pull origin master
        git add dyno/bin/
        git commit -m "Build Windows executable" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    needs: build-windows
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v4
      timeout-minutes: 5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      timeout-minutes: 5
      with:
        python-version: '3.10'
    
    - name: Install cx_Freeze
      timeout-minutes: 10
      run: |
        pip install --timeout 600 -v --no-cache-dir cx_Freeze~=6.15.9

    - name: Install pyserial
      timeout-minutes: 10
      run: |
        pip install --timeout 600 -v --no-cache-dir pyserial~=3.5

    - name: Install matplotlib
      timeout-minutes: 10
      run: |
        pip install --timeout 600 -v --no-cache-dir matplotlib~=3.9.3
    
    - name: Create setup.py
      run: |
        cat > setup.py << 'EOL'
        from cx_Freeze import setup, Executable
        
        setup(
            name="dyno",
            version="1.0",
            executables=[
                Executable(
                    "dyno/dyno.py",
                    target_name="dyno",
                    base="console"
                )
            ]
        )
        EOL

    - name: Build executable
      timeout-minutes: 10
      shell: bash
      run: |
        python setup.py build
        mkdir -p dyno/bin
        mv build/exe.macos*/dyno dyno/bin/dyno-mac
        chmod +x dyno/bin/dyno-mac
    
    - name: Configure Git and Push
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git pull origin master
        git add dyno/bin/
        git commit -m "Build macOS executable" || echo "No changes to commit"
        git push origin HEAD:${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
